package com.mal.cloud.future_auth.data.exceptions

class AuthFailedException(message: String) : RuntimeException(message) {

}